export const actionTypes = {
  FINDREPOS: 'FINDREPOS',
  SETREPOS: 'SETREPOS',
  ERRORREPOS: 'ERRORREPOS',
  EMPTYREPOS: 'EMPTYREPOS',
  PENDINGREPOS: 'PENDINGREPOS',
  ADDFAVORITES: 'ADDFAVORITES',
  REMOVEFAVORITES: 'REMOVEFAVORITES',
  SETFAVORITESREPOS: 'SETFAVORITESREPOS',
};
export const baseUrl = 'https://api.github.com';
